version: "3.2"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/topfrag_api
    stdin_open: true
    tty: true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/topfrag_frontend
      - /topfrag_frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
